[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "xsec"
version = "0.1.0"
description = "cross-sectional analysis tool"
readme = "README.md"
license = { text = "GPL-3.0-or-later" } # thanks gmsh
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.0",
    "scipy>=1.10",
    "pyvista>=0.40",
    "gmsh>=4.11",
    "meshio>=5.3.5",
]

# Optional dependencies for development/testing
[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]

[project.scripts]
go = "xsec.__main__:main"

[tool.pytest.ini_options]
pythonpath = ["src"]

